spring.application.name=file-storage-system
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

aws.region=${AWS_REGION:us-east-1}
aws.s3.bucket=${AWS_S3_BUCKET:change-me-bucket}
aws.s3.upload-url-ttl-seconds=${AWS_UPLOAD_URL_TTL_SECONDS:900}
aws.s3.download-url-ttl-seconds=${AWS_DOWNLOAD_URL_TTL_SECONDS:300}
